### ISSUE TITLE
観戦者が奈落で死ぬとプレイ中の人が死んだ判定になる。

### ISSUE THREAD

**Issue by Megumiso** [GiganticMinecraft/Petra#12]
おかげでWave6(生き残るやつ)で生き残ってるのにゲームオーバーになる現象が発生している模様。

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/Petra/blob/51d9ab45898fc9783539c62e6751575dc39e657a/src/main/kotlin/click/seichi/petra/stage/section/wave/SurviveWave.kt#L93-L100
ここで死んだプレイヤーが観戦者なのか実際のプレイヤーなのかを区別してないから？
