### ISSUE TITLE
build fails on ghactions

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/Petra#20]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processResources'.
> Entry petra.yml is a duplicate but no duplicate handling strategy has been set. Please refer to docs.gradle.org/7.3.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

**Comment by Lucky3028** [comment]
多分 #23 で修正された
