### ISSUE TITLE
ハロウィンイベントに向けた修正

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/Petra#4]
そろそろまとめなきゃ？と思い。

イベント詳細↓
https://www.seichi.network/post/halloween2020

モンスター討伐イベントとしての使用を想定。
今のところ、１０月の土日でやりたいね～以外は特に決まっていない。
Just ideaですが、ウェーブを実質エンドレスにしてどこまで耐えられるかによって報酬が！！！とか面白そう。

**Comment by Lucky3028** [comment]
特にそんなに変えてほしいところがある！というわけではないんですよね。
今のところはこれくらいです。
* プレイヤー数に対応して敵Mobの湧き具合が変わると思うんですが、プレ公開みたいなときは流石に多すぎたので、割合を半分くらいにする
* 敵がかぼちゃをかぶる

**Comment by Lucky3028** [comment]
「ウェーブを実質エンドレスにしてどこまで耐えられるか」は発想としても面白いんですが、終わりが見えないというのは単純にきついのでは？

**Comment by unchama** [comment]
敵モブの沸き具合は実はプレ公開中に修正版がリアルタイムに反映、調整されていて、今の版はかなりマシになってる認識です

**Comment by unchama** [comment]
難易度部分は報酬をどうするか？次第で調整かなと思ってます。単純クリアだと現状のバランスだとたぶん普通に行けそう

**Comment by Lucky3028** [comment]
なるほど、それなら特に変えることはないかもしれないですね。報酬の内容に関しては別にここで議論することですかね？（Discordのplugin開発チャンネルにそのまま流れてるのでうるさそう）

**Comment by Lucky3028** [comment]
特に変えることはないというか、そういうことになると「ウェーブを実質エンドレスにしてどこまで耐えられるか」もよさそう
