### ISSUE TITLE
クリア者のUUIDを記録する

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/Petra#6]
ハロウィンイベント用

**Comment by tar0ss** [comment]
UUIDだけでいいのか？
playername : UUID
のほうがよい？

**Comment by tar0ss** [comment]
playername list とuuid list両方もつ

**Comment by Lucky3028** [comment]
どっちもの方がいいですね

**Comment by tar0ss** [comment]
petra.yml の savewinner をtrueにすれば次のゲームから勝者が記録されるように
